import type { Customer } from "./customer";

export const sampleCustomers: Customer[] = [
  {
    id: "customer_musteragentur_berlin",
    name: "Musteragentur Berlin",
    contactName: "Jonas Becker",
    email: "mail@musteragentur.de",
    phone: "+49 30 123456",
    street: "Invalidenstrasse 45",
    postalCode: "10115",
    city: "Berlin",
    countryCode: "DE",
    paymentTermsDays: 14,
    defaultVatRatePercent: 19,
    defaultCurrency: "EUR",
    internalNotes: "Bevorzugt PDF per E-Mail.",
  },
  {
    id: "customer_schneider_it",
    name: "Schneider IT Beratung",
    contactName: "Anna Schmidt",
    email: "kontakt@schneider.de",
    phone: "+49 69 987654",
    street: "Hansaallee 8",
    postalCode: "60322",
    city: "Frankfurt am Main",
    countryCode: "DE",
    vatId: "DE123456789",
    paymentTermsDays: 14,
    defaultVatRatePercent: 19,
    defaultCurrency: "EUR",
    internalNotes: "Technische Beratung, meist kurze Projektphasen.",
  },
  {
    id: "customer_atelier_nord",
    name: "Atelier Nord GmbH",
    contactName: "Max Mustermann",
    email: "info@atelier-nord.de",
    phone: "+49 40 12345678",
    street: "Kanalstrasse 19",
    postalCode: "20359",
    city: "Hamburg",
    countryCode: "DE",
    vatId: "DE123456789",
    taxNumber: "17/123/45678",
    paymentTermsDays: 14,
    defaultVatRatePercent: 19,
    defaultCurrency: "EUR",
    internalNotes:
      "Wichtiger Kunde. Arbeitet an Retainer-Projekten. Bevorzugt PDF per E-Mail.",
  },
];
